version: '3.9'

services:
  cosmos-adapter:
    image: node:16-alpine
    entrypoint: ["/bin/sh", "-c", "yarn start:dev --preserveWatchOutput"]
    working_dir: /app
    volumes:
      - ../cosmos-rosetta-typescript:/app
    ports:
      - 3000:3000